# Generated by Django 4.1.2 on 2022-10-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabDecks', '0003_alter_card_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='desciption',
            new_name='description',
        ),
    ]
