# Generated by Django 4.1.2 on 2022-10-14 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabDecks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desciption', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='cards',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabDecks.deck'),
        ),
    ]
