# Generated by Django 4.1.2 on 2022-10-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabDecks', '0002_deck_card_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabDecks.deck'),
        ),
    ]
