# Generated by Django 4.1.2 on 2022-10-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabDecks', '0006_card_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='imageURL',
            field=models.CharField(blank=True, max_length=20482),
        ),
    ]
